//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class footer
    {
        public int id { get; set; }
        public string Recent_News { get; set; }
        public string For_Customers { get; set; }
        public string Contact_Us { get; set; }
    }
}
