//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class İletişim
    {
        public int id { get; set; }
        public string Adres { get; set; }
        public string Email { get; set; }
        public string TelN { get; set; }
        public string Whatsapp { get; set; }
        public string Fax { get; set; }
    }
}
