//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class otelyönetimiEntities : DbContext
    {
        public otelyönetimiEntities()
            : base("name=otelyönetimiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> About { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<footer> footer { get; set; }
        public virtual DbSet<galeri> galeri { get; set; }
        public virtual DbSet<Hakkımızda> Hakkımızda { get; set; }
        public virtual DbSet<Home> Home { get; set; }
        public virtual DbSet<İletişim> İletişim { get; set; }
        public virtual DbSet<Oda> Oda { get; set; }
        public virtual DbSet<OdaTürü> OdaTürü { get; set; }
        public virtual DbSet<Rezervasyon> Rezervasyon { get; set; }
        public virtual DbSet<RezervasyonDurumu> RezervasyonDurumu { get; set; }
        public virtual DbSet<room> room { get; set; }
        public virtual DbSet<Service1> Service1 { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
