//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oda
    {
        public int id { get; set; }
        public Nullable<int> RezervasyonDurumuid { get; set; }
        public Nullable<int> OdaTürüid { get; set; }
        public string OdaNumarası { get; set; }
        public string OdaÜcreti { get; set; }
        public string Kapasite { get; set; }
    }
}
