//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervasyon
    {
        public int id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Adres { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> VarışTarihi { get; set; }
        public Nullable<System.DateTime> AyrılışTarihi { get; set; }
        public string KonukSayısı { get; set; }
        public Nullable<int> OdaTürüid { get; set; }
        public Nullable<int> RezervasyonDurumuid { get; set; }
    }
}
