//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class room
    {
        public int id { get; set; }
        public string Başlık { get; set; }
        public string Resim { get; set; }
        public string Açıklama { get; set; }
        public string Fiyat { get; set; }
    }
}
