//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service1
    {
        public int id { get; set; }
        public string başlık1 { get; set; }
        public string açıklama1 { get; set; }
        public string resim1 { get; set; }
    }
}
